"use client";

import { ArrowLeft, CheckCircle2, FileCheck2 } from "lucide-react";
import { useState } from "react";
import { Link } from "@/components/router-link";
import { useDemo } from "@/lib/demo/store";

export default function KycPage() {
  const { kyc, submitKyc } = useDemo(); const [fullName, setFullName] = useState(kyc.fullName); const [country, setCountry] = useState(kyc.country); const [documentNumber, setDocumentNumber] = useState(kyc.documentNumber); const [submitted, setSubmitted] = useState(false);
  function submit() { submitKyc({ fullName, country, documentType: "National ID", documentNumber }); setSubmitted(true); }
  return <main className="mx-auto max-w-3xl px-5 py-8 sm:px-8"><Link href="/app" className="text-sm font-bold text-[#718071]"><ArrowLeft className="mr-2 inline h-4 w-4" />Back to dashboard</Link><div className="mt-10 rounded-3xl border border-[#e2e8e0] bg-white p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#85a933]">Identity verification</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.04em]">Verify your identity</h2><p className="mt-3 text-[#758075]">This KYC process is for the product demo and does not connect to a real provider.</p>{kyc.status === "APPROVED" || submitted ? <div className="mt-9 rounded-2xl bg-[#f2f9df] p-6"><CheckCircle2 className="h-7 w-7 text-[#75a922]" /><p className="mt-4 text-lg font-bold">{kyc.status === "APPROVED" ? "Identity verified" : "Under review"}</p><p className="mt-2 text-sm leading-6 text-[#748071]">{kyc.status === "APPROVED" ? "Your trading features are unlocked." : "An admin can now review this submission."}</p></div> : <div className="mt-9 space-y-5"><label className="block text-sm font-bold">Full name<input value={fullName} onChange={(event) => setFullName(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe6dc] bg-transparent px-4 py-3 outline-none focus:border-[#b2de4f]" /></label><label className="block text-sm font-bold">Country<input value={country} onChange={(event) => setCountry(event.target.value)} placeholder="Kenya" className="mt-2 w-full rounded-xl border border-[#dfe6dc] bg-transparent px-4 py-3 outline-none focus:border-[#b2de4f]" /></label><label className="block text-sm font-bold">National ID number<input value={documentNumber} onChange={(event) => setDocumentNumber(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe6dc] bg-transparent px-4 py-3 outline-none focus:border-[#b2de4f]" /></label><div className="rounded-xl bg-[#f7faf4] p-4 text-sm text-[#748071]"><FileCheck2 className="mr-2 inline h-4 w-4 text-[#75a922]" />Secure document upload is required.</div><button onClick={submit} className="w-full rounded-xl bg-[#b2de4f] px-5 py-3.5 text-sm font-bold text-[#24300f]">Submit for review</button></div>}</div></main>;
}
