import { useState } from "react";
import { Bot, MessageCircle, Send, X } from "lucide-react";

type Message = { role: "assistant" | "user"; text: string };

function demoAnswer(input: string) {
  const question = input.toLowerCase();
  if (question.includes("loss") || question.includes("risk")) return "Trading can result in partial or total loss. Start small, use a stop plan, and never trade money you cannot afford to lose. Read the Trading Policy before placing an order.";
  if (question.includes("deposit") || question.includes("fund")) return "Open Wallet from the mobile navigation or sidebar to review the deposit flow. In this demo, balances activate after a completed simulated deposit.";
  if (question.includes("chart") || question.includes("candle")) return "Use the chart controls on Trade to switch between candles, line, area, and volume views. Prices are simulated and update every 1.5 seconds.";
  return "I can explain the charts, simulated trading, deposits, withdrawals, account setup, and risk controls. What would you like to understand?";
}

export function Chatbot() {
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: "Hi, I’m the Derivix assistant. I can explain the platform and trading concepts, but I do not provide financial advice." }]);
  async function send() { const text = input.trim(); if (!text) return; setMessages((current) => [...current, { role: "user", text }]); setInput(""); const endpoint = import.meta.env.VITE_AI_ASSISTANT_URL; if (endpoint) { try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text }) }); const data = await response.json() as { message?: string; reply?: string }; setMessages((current) => [...current, { role: "assistant", text: data.reply ?? data.message ?? demoAnswer(text) }]); return; } catch { /* keep the local help response available when the AI service is unavailable */ } } setMessages((current) => [...current, { role: "assistant", text: demoAnswer(text) }]); }
  return <div className="fixed bottom-24 right-4 z-[80] sm:bottom-6 sm:right-6"><button type="button" aria-label={open ? "Close Derivix assistant" : "Open Derivix assistant"} onClick={() => setOpen((current) => !current)} className="flex h-14 w-14 items-center justify-center rounded-full bg-brand-ink text-brand-lime shadow-[0_14px_34px_rgba(17,19,18,0.25)] transition-transform hover:scale-105 dark:bg-brand-lime dark:text-brand-ink">{open ? <X className="h-6 w-6" /> : <MessageCircle className="h-6 w-6" />}</button>{open && <section className="absolute bottom-16 right-0 flex h-[min(520px,calc(100vh-10rem))] w-[min(360px,calc(100vw-2rem))] flex-col overflow-hidden rounded-3xl border border-brand-line bg-white shadow-2xl dark:bg-dark-ink"><header className="flex items-center gap-3 border-b border-brand-line bg-brand-canvas px-4 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand-lime/20 text-brand-limeDeep"><Bot className="h-5 w-5" /></span><div><p className="text-sm font-bold text-brand-ink">Derivix assistant</p><p className="text-[11px] text-brand-muted">AI-ready help desk · demo responses</p></div></header><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`max-w-[88%] rounded-2xl px-3 py-2.5 text-xs leading-5 ${message.role === "user" ? "ml-auto bg-brand-ink text-white" : "bg-brand-canvas text-brand-ink"}`}>{message.text}</div>)}</div><div className="border-t border-brand-line p-3"><div className="flex items-center gap-2 rounded-xl border border-brand-line bg-brand-canvas p-1"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") send(); }} placeholder="Ask about Derivix..." className="min-w-0 flex-1 bg-transparent px-2 py-2 text-xs text-brand-ink outline-none" /><button type="button" aria-label="Send message" onClick={send} className="rounded-lg bg-brand-lime p-2 text-brand-ink"><Send className="h-4 w-4" /></button></div><p className="mt-2 text-[10px] leading-4 text-brand-muted">Educational support only. The assistant is not a broker or financial adviser.</p></div></section>}</div>;
}
