import { BarChart3, BriefcaseBusiness, FileText, LayoutDashboard, Menu, Settings2, ShieldCheck, UserRound, Wallet } from "lucide-react";
import { useState } from "react";
import { Link } from "@/components/router-link";

const items = [{ label: "Home", href: "/app", icon: LayoutDashboard }, { label: "Markets", href: "/app/markets", icon: BarChart3 }, { label: "Positions", href: "/app/positions", icon: BriefcaseBusiness }, { label: "Wallet", href: "/app/deposit", icon: Wallet }];
const moreItems = [{ label: "Trade", href: "/app/trade", icon: BarChart3 }, { label: "Transactions", href: "/app/transactions", icon: FileText }, { label: "Verification", href: "/app/kyc", icon: ShieldCheck }, { label: "Profile", href: "/app/profile", icon: UserRound }, { label: "Settings", href: "/app#settings", icon: Settings2 }];

export function MobileNav() {
  const [open, setOpen] = useState(false);
  return <><nav aria-label="Mobile navigation" className="fixed inset-x-3 bottom-3 z-30 flex justify-around rounded-2xl border border-[#e0e7de] bg-white/95 px-1 py-2 shadow-[0_16px_40px_rgba(17,19,18,0.14)] backdrop-blur transition-colors sm:inset-x-6 lg:hidden">{items.map(({ label, href, icon: Icon }) => <Link key={label} href={href} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl px-1 py-2 text-[10px] font-bold text-[#7d867d] transition-colors"><Icon className="h-[18px] w-[18px]" />{label}</Link>)}<button type="button" aria-label="Open more navigation" aria-expanded={open} onClick={() => setOpen(true)} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl px-1 py-2 text-[10px] font-bold text-[#7d867d]"><Menu className="h-[18px] w-[18px]" />More</button></nav>{open && <div className="fixed inset-0 z-50 bg-black/40 lg:hidden" onClick={() => setOpen(false)}><section role="dialog" aria-label="More navigation" className="absolute inset-x-0 bottom-0 rounded-t-3xl border-t border-brand-line bg-white p-5 pb-28 shadow-2xl dark:bg-dark-ink" onClick={(event) => event.stopPropagation()}><div className="mx-auto mb-5 h-1.5 w-12 rounded-full bg-brand-line" /><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-muted">More workspace</p><h2 className="mt-1 text-xl font-bold text-brand-ink">Tools and account</h2></div><button type="button" onClick={() => setOpen(false)} className="rounded-full bg-brand-canvas px-3 py-2 text-xs font-bold text-brand-muted">Close</button></div><div className="mt-5 grid grid-cols-2 gap-3">{moreItems.map(({ label, href, icon: Icon }) => <Link key={label} href={href} onClick={() => setOpen(false)} className="flex items-center gap-3 rounded-2xl border border-brand-line bg-brand-canvas px-4 py-4 text-sm font-bold text-brand-ink"><Icon className="h-5 w-5 text-brand-limeDeep" />{label}</Link>)}</div></section></div>}</>;
}
