"use client";

import { useState } from "react";
import { ArrowLeft, CheckCircle2, UserRound } from "lucide-react";
import { Link } from "@/components/router-link";
import { useAuth } from "@/lib/auth/store";

export default function ProfilePage() {
  const { user, updateProfile } = useAuth(); const metadata = user?.user_metadata ?? {}; const [fullName, setFullName] = useState(String(metadata.full_name ?? "")); const [phone, setPhone] = useState(String(metadata.phone ?? "")); const [country, setCountry] = useState(String(metadata.country ?? "Kenya")); const [message, setMessage] = useState("");
  async function save() { const result = await updateProfile({ fullName, phone, country }); setMessage(result.error ?? "Profile updated successfully."); }
  return <main className="mx-auto max-w-3xl px-5 py-8 sm:px-8"><Link href="/app" className="text-sm font-bold text-brand-muted"><ArrowLeft className="mr-2 inline h-4 w-4" />Back to dashboard</Link><div className="mt-10 rounded-3xl border border-brand-line bg-white p-6 dark:bg-dark-ink sm:p-10"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-lime/20 text-brand-limeDeep"><UserRound className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-limeDeep">Account settings</p><h2 className="mt-1 text-3xl font-bold tracking-tight text-brand-ink">Your profile</h2></div></div><p className="mt-4 text-sm text-brand-muted">These details are saved to your Supabase profile record.</p><div className="mt-9 space-y-5"><label className="block text-sm font-bold text-brand-ink">Full name<input value={fullName} onChange={(event) => setFullName(event.target.value)} className="mt-2 w-full rounded-xl border border-brand-line bg-transparent px-4 py-3 text-brand-ink outline-none focus:border-brand-lime" /></label><label className="block text-sm font-bold text-brand-ink">Email<input value={user?.email ?? ""} readOnly className="mt-2 w-full rounded-xl border border-brand-line bg-brand-canvas px-4 py-3 text-brand-muted outline-none" /></label><label className="block text-sm font-bold text-brand-ink">Phone<input value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-2 w-full rounded-xl border border-brand-line bg-transparent px-4 py-3 text-brand-ink outline-none focus:border-brand-lime" /></label><label className="block text-sm font-bold text-brand-ink">Country<input value={country} onChange={(event) => setCountry(event.target.value)} className="mt-2 w-full rounded-xl border border-brand-line bg-transparent px-4 py-3 text-brand-ink outline-none focus:border-brand-lime" /></label>{message && <p className="rounded-xl bg-brand-lime/15 p-3 text-sm font-bold text-brand-limeDeep"><CheckCircle2 className="mr-2 inline h-4 w-4" />{message}</p>}<button onClick={save} className="rounded-xl bg-brand-lime px-5 py-3.5 text-sm font-bold text-brand-ink">Save profile</button></div></div></main>;
}
